version: "3.9"

services:
  postgres:
    image: postgres:15.3-bullseye
    restart: always
    environment:
      - POSTGRES_DB=psql
      - POSTGRES_USER=psql
      - POSTGRES_PASSWORD=psql
    volumes:
      - todo-db:/var/lib/postgresql/data
      - db-backup:/db-backup
    networks:
      - internal

  app:
    build:
      dockerfile: spending-app-dockerfile
    command: [
        # wait for postgres to be up
        "./wait-for-it.sh",
        "postgres:5432",
        "--strict",
        "--",
        "./run-app.sh",
      ]
    networks:
      - internal
      - nginx-proxy-manager

volumes:
  todo-db:
  db-backup:

networks:
  # name of your reverse proxy network
  nginx-proxy-manager:
    external: true
    name: nginx-proxy-manager
  # used so services can communicate with each other
  internal:
